extends: populist
rules:
  brace-style:
    - error
    - stroustrup
    - allowSingleLine: true
  indent:
    - error
    - 2
    - SwitchCase: 1
      VariableDeclarator:
        var: 2
        let: 2
        const: 3
  no-console: off
  no-mixed-requires: off
  no-sync: off
  valid-jsdoc: off
